FROM golang:1.19-rc-buster

RUN apt update && \
	apt install -y zlib1g-dev

RUN cd /go && \
	wget https://github.com/protocolbuffers/protobuf/releases/download/v21.2/protobuf-all-21.2.tar.gz -O protobuf-all-21.2.tar.gz && \
	tar -zxvf protobuf-all-21.2.tar.gz && rm protobuf-all-21.2.tar.gz && \
	cd protobuf-21.2 && ./configure -prefix=/usr/local/protobuf && make && make install

RUN go env -w GO111MODULE=on && \
	go env -w GOPROXY=https://proxy.golang.org,direct

ENV PATH="/usr/local/protobuf/bin:$PATH" \
	LD_LIBRARY_PATH="/usr/local/protobuf/lib"

WORKDIR /go